### ISSUE TITLE
npm package not found

### ISSUE THREAD

**Issue by dheeraj0818** [paytmmoney/jsPMClient#11]
npm install pmClient

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/pmClient - Not found
npm ERR! 404
npm ERR! 404  'pmClient@*' is not in this registry.
npm ERR! 404 This package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by anurag-roy** [comment]
Yeah same, could not find it on the NPM registry. What a joke!

Best bet is to clone the repo and install it as a local package

**Comment by sachinyadav10** [comment]
It is not on npm yet you have to clone the repo. Readme is updated. 

[https://github.com/paytmmoney/jsPMClient/blob/master/README.md](Readme)
